user:
  max_length_name: 32
  min_length_password: 6
course:
  max_length_name: 32
  max_length_content: 5000
subject:
  max_length_name: 32
  max_length_details: 1024
task:
  max_length_title: 128
  max_length_content: 10000
per_page: 4
cols: 4
status_type: ["submitted", "passed"]
finish: "finish"
status_0: 0
order_1: 1
status_2: 2
deleted_1: 1
type_deleted: ["true", "false"]
